# Generated by Django 3.1.1 on 2020-11-23 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pdj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passbook',
            fields=[
                ('passbook_id', pdj.models.BigAutoField(help_text='通帳ID', primary_key=True, serialize=False)),
                ('passbook_type', pdj.models.EnumField(choices=[('USE', '使用'), ('GET', '取得')], max_length=3)),
                ('amount', models.IntegerField(help_text='金額')),
                ('recording_date', models.DateField(help_text='記録日')),
                ('user', models.ForeignKey(help_text='ユーザー', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passbook',
            },
        ),
    ]
